version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?connect_timeout=300
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src